### ISSUE TITLE
ss-local redir tproxy for udp huge delay of processing packets

### ISSUE THREAD

**Issue by notsure2** [shadowsocks/shadowsocks-rust#350]
Hello,
Compiled ss-local from latest master, using in tproxy redir mode. Using similar iptables rules as in shadowsocks-libev README.md for setting up TPROXY.

In case of UDP, the packet arrives in localhost instantly, but ss-local is not processing the packet (or seems there's a huge delay in reading from the tproxy socket) except after huge delay (10+ seconds) leading the sender of the packet to timeout and later ignore the response.

ss-libev works fine for the same exact case.

**Comment by notsure2** [comment]
ss-server also. As of latest commit https://github.com/shadowsocks/shadowsocks-rust/commit/bc33723107dce4d128ba53457228ecb3a0c6c5a5 it's completely broken...

It's randomly sitting and not reading from the socket.....

**Comment by zonyitoo** [comment]
It only happens in UDP relay? Everything works fine for TCP relay?

**Comment by notsure2** [comment]
It happens in TCP relay also, but less frequent.

**Comment by zonyitoo** [comment]
Please run `sslocal` again with `-vvv` command line options and checkout if you could see this line

https://github.com/shadowsocks/shadowsocks-rust/blob/bc33723107dce4d128ba53457228ecb3a0c6c5a5/crates/shadowsocks-service/src/local/redir/udprelay/mod.rs#L92-L97

**Comment by notsure2** [comment]
Yes, I did that already, that line only appears after the long delay passed.

**Comment by zonyitoo** [comment]
> ss-server also. As of latest commit bc33723 it's completely broken...

`ssserver` doesn't have anything related to redir. What did you mean about `also`?

**Comment by zonyitoo** [comment]
> Yes, I did that already, that line only appears after the long delay passed. It is hanging before this point... When this message is written the packet is processed immediately.

Ok. There must be something related to tokio v0.3's `AsyncFd`'s event processing.

**Comment by notsure2** [comment]
I mean I am also seeing hang from ss-server connections time out, not responding to connections. It maybe a common issue in both server and redir, not specific to redir itself...

It seems like a general issue in socket not getting notified of presence of data except after long time.

**Comment by zonyitoo** [comment]
> I mean I am also seeing hang from ss-server connections time out, not responding to connections. 

Both TCP and UDP?

That's strange. I just have done some performance check with `sslocal`'s tunnel mode and `ssserver`, everything works fine during test.

**Comment by notsure2** [comment]
Yes, both TCP and UDP

**Comment by zonyitoo** [comment]
Did you compile binaries with `--release`?

**Comment by notsure2** [comment]
Yes. here's my binaries:

[release.zip](https://github.com/shadowsocks/shadowsocks-rust/files/5721944/release.zip)

**Comment by zonyitoo** [comment]
Couldn't reproduce that on my RPI. Here is how I tried:

0. Install a brand new Raspbian Linux in RPI.

1. Run `sslocal` with

```
sudo ./sslocal -b "0.0.0.0:60080" -s "xx:xx" -m "chacha20-ietf-poly1305" -k "xx" --protocol redir --outbound-fwmark 255 -U --tcp-redir tproxy --udp-redir tproxy -vv
```

2. Set `net.ipv4.ip_forward = 1` in `/etc/sysctl.conf`

3. Run [`iptables_tproxy.sh`](https://github.com/shadowsocks/shadowsocks-rust/blob/master/configs/iptables_tproxy.sh).

4. Run

```
dig @8.8.8.8 www.google.com

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> @8.8.8.8 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35352
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		126	IN	A	172.217.161.164

;; Query time: 414 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Dec 21 12:20:04 GMT 2020
;; MSG SIZE  rcvd: 59
```

You can see `Query time: 414 msec`. Just ignore the server's latency :(.

**Comment by zonyitoo** [comment]
Oh. Finally, it is reproduced!

**Comment by zonyitoo** [comment]
Don't know why, but it have been magically fixed in the current master branch. Please check if it is work in your env.

**Comment by notsure2** [comment]
No it's not solved. Especially UDP (tcp seems maybe fixed). Just test with iperf3 UDP mode. Also, why I can't compile shadowsocks-rust with stable rust toolchain ? Why using nightly toolchain ? How to know if this is bug in toolchain or bug in shadowsocks...

**Comment by zonyitoo** [comment]
> Why using nightly toolchain ?

Because [shadowsocks-crypto](https://github.com/shadowsocks/shadowsocks-crypto) requires some non-released features in stdsimd for hardware accleration.

**Comment by madeye** [comment]
@LuoZijun @zonyitoo it looks we cannot avoid nightly toolchain if we move on with a pure rust crypto library.

What about fixing the toolchain to a specific version of nightly build, say nightly-2020-12-20? It should improve our CI flow by providing a reproducible building environment.

**Comment by LuoZijun** [comment]
@madeye 

我觉得可以，可以添加一个 `rust-toolchain`  到根目录。

```bash
touch rust-toolchain;
echo "nightly-2020-12-20" > rust-toolchain;

```

**Comment by zonyitoo** [comment]
> No it's not solved. Especially UDP (tcp seems maybe fixed). Just test with iperf3 UDP mode. Also, why I can't compile shadowsocks-rust with stable rust toolchain ? Why using nightly toolchain ? How to know if this is bug in toolchain or bug in shadowsocks...

Could you provide steps about how to reproduce your issue with UDP mode? I tested with iperf3 UDP mode, everything works fine.

**Comment by notsure2** [comment]
1. Setup a shadowsocks-rust server.
2. Setup a ss-local SOCKS5 client then use tun2socks to tunnel traffic through it (NOTE: I am always using shadowsocks-libev as the client to avoid confusion of issues between client and server).
3. Setup an iperf3 server that is reachable through shadowsocks-rust server.
4. iperf3 -c the-iperf3-server -p the-iperf3-port -u -t 60 -R -b 1M
5. It will very randomly work and stop working. When it works, it will work immediately, when it doesn't work, iperf3 will wait for a long time for data to be received and then give up with "Resource temporarily unavailable".

Same exact setup except use ss-libev: always working without fail.

The problem is that it's very difficult due to moving toolchain and moving code to get a reproducible result... I will retry again with the latest commit on master and latest nightly toolchain.

**Comment by notsure2** [comment]
OK I'm seeing this even without shadowsocks-rust now, I'll check tun2socks and other parts of my setup and report back.

**Comment by notsure2** [comment]
@zonyitoo ok after finding and fixing a problem with Cloak, and thoroughly retesting again, I'm not able to make the issue appear. I'll reopen this bug if I run into it again.
