### ISSUE TITLE
[Panic/Error] ssserver + v2ray-plugin

### ISSUE THREAD

**Issue by peylight** [shadowsocks/shadowsocks-rust#447]
Hi,
I try to use ssserver with [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin) but this error happened:

```
# RUST_BACKTRACE=full /usr/local/bin/ssserver -c /etc/shadowsocks-libev/config.json 
2021-03-08T14:12:27.814097378-05:00 INFO  shadowsocks 1.9.2
2021-03-08T14:12:27.820906044-05:00 INFO  shadowsocks tcp server listening on 127.0.0.1:35907, inbound address 192.168.20.110:1080
2021/03/08 14:12:27 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
2021/03/08 14:12:27 A unified platform for anti-censorship.
2021/03/08 14:12:27 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 35907 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:35907 > listen tcp 127.0.0.1:35907: bind: address already in use
2021-03-08T14:12:27.987820355-05:00 ERROR plugin exited with status: exit code: 1
thread 'main' panicked at 'aborted with server exited unexpectly', bin/ssserver.rs:306:45
stack backtrace:
   0:     0x55e9d5e5e26a - std::backtrace_rs::backtrace::libunwind::trace::hb4de9797f80b7b8c
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55e9d5e5e26a - std::backtrace_rs::backtrace::trace_unsynchronized::h59566d0bd20efff7
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e9d5e5e26a - std::sys_common::backtrace::_print_fmt::hcfa5ce6be50275d4
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e9d5e5e26a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8c307a38b9bab04
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55e9d5ca954c - core::fmt::write::h3868db8542c90941
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/core/src/fmt/mod.rs:1096:17
   5:     0x55e9d5e5d9e1 - std::io::Write::write_fmt::hab90295d5a0f197d
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/io/mod.rs:1568:15
   6:     0x55e9d5e5d410 - std::sys_common::backtrace::_print::h19224910b8700cf1
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55e9d5e5d410 - std::sys_common::backtrace::print::h25dedfa68c5fb84a
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55e9d5e5d410 - std::panicking::default_hook::{{closure}}::h12c5765653a72a42
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:208:50
   9:     0x55e9d5e5c987 - std::panicking::default_hook::he65cee71c4209f0c
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:225:9
  10:     0x55e9d5e5c987 - std::panicking::rust_panic_with_hook::h01a674d863fe0d8a
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:591:17
  11:     0x55e9d5e7b01d - std::panicking::begin_panic_handler::{{closure}}::h9b9fecf185178864
  12:     0x55e9d5e7af8c - std::sys_common::backtrace::__rust_end_short_backtrace::h57be46a42dc7f24b
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55e9d5e7af3d - rust_begin_unwind
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:493:5
  14:     0x55e9d5e5d110 - std::panicking::begin_panic_fmt::h12277576db89392f
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:435:5
  15:     0x55e9d5c2308e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h73e1e5e6d0ad4c69
  16:     0x55e9d5c47a47 - ssserver::main::hc9c5e1c75156f579
  17:     0x55e9d5bec266 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4006b27fbd5b2c1f
  18:     0x55e9d5c4d3f8 - main
  19:     0x7f2b96a6509b - __libc_start_main
  20:     0x55e9d5bd0b29 - _start
  21:                0x0 - <unknown>
Aborted

```

my config.json file:
```
{
    "server": "192.168.20.110",
    "server_port": 1080,
    "local_address": "127.0.0.1",
    "local_port": 1088,
    "password": "123456",
    "plugin": "v2ray-plugin",
    "method": "chacha20-ietf-poly1305"
}
```

**Comment by zonyitoo** [comment]
```
failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 35907 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:35907 > listen tcp 127.0.0.1:35907: bind: address already in use
```

There was some other programs running on your server?

Port `35907` was choosen randomly. Maybe there was a program uses this port, for example, an `accept`ed socket.

Try to restart it again and see if the problem still exists.

**Comment by peylight** [comment]
No every time i run it, the port has changed randomly with the same error.
I had to use [go-shadowsocks2](https://github.com/shadowsocks/go-shadowsocks2) and the problem has gone.

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/go-shadowsocks2/blob/956d34541c262edaad1ff55776ff2e27eeca0789/plugin.go#L15-L37

It has exactly the same process as this project:

https://github.com/shadowsocks/shadowsocks-rust/blob/7700c94ae044fae6f704d23353691eb04bf571b2/crates/shadowsocks/src/plugin/mod.rs#L70-L114

**Comment by zonyitoo** [comment]
Oh.. I know why.

```json
{
    "server": "192.168.20.110",
    "server_port": 1080,
    "local_address": "127.0.0.1",
    "local_port": 1088,
    "password": "123456",
    "plugin": "v2ray-plugin",
    "method": "chacha20-ietf-poly1305"
}
```

Delete `local_address` and `local_port` in the configuration.

**Comment by zonyitoo** [comment]
It should be fixed without surprise. Closing but still allow further discussion.

**Comment by peylight** [comment]
I remove the `local_address` and `local_port` from `config.json` file but still have the problem:
```
# RUST_BACKTRACE=full /usr/local/bin/ssserver --log-without-time -c /etc/shadowsocks-rust/config.json 
INFO  shadowsocks 1.9.2
INFO  shadowsocks tcp server listening on 127.0.0.1:12905, inbound address 192.168.20.110:1080
2021/03/09 12:45:34 V2Ray 4.23.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.3 linux/amd64)
2021/03/09 12:45:34 A unified platform for anti-censorship.
2021/03/09 12:45:34 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 12905 > v2ray.com/core/transport/internet: failed to listen on address: 127.0.0.1:12905 > listen tcp 127.0.0.1:12905: bind: address already in use
ERROR plugin exited with status: exit code: 1
thread 'main' panicked at 'aborted with server exited unexpectly', bin/ssserver.rs:306:45
stack backtrace:
   0:     0x55d30e1e826a - std::backtrace_rs::backtrace::libunwind::trace::hb4de9797f80b7b8c
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d30e1e826a - std::backtrace_rs::backtrace::trace_unsynchronized::h59566d0bd20efff7
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d30e1e826a - std::sys_common::backtrace::_print_fmt::hcfa5ce6be50275d4
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d30e1e826a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd8c307a38b9bab04
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d30e03354c - core::fmt::write::h3868db8542c90941
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/core/src/fmt/mod.rs:1096:17
   5:     0x55d30e1e79e1 - std::io::Write::write_fmt::hab90295d5a0f197d
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/io/mod.rs:1568:15
   6:     0x55d30e1e7410 - std::sys_common::backtrace::_print::h19224910b8700cf1
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d30e1e7410 - std::sys_common::backtrace::print::h25dedfa68c5fb84a
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d30e1e7410 - std::panicking::default_hook::{{closure}}::h12c5765653a72a42
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:208:50
   9:     0x55d30e1e6987 - std::panicking::default_hook::he65cee71c4209f0c
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:225:9
  10:     0x55d30e1e6987 - std::panicking::rust_panic_with_hook::h01a674d863fe0d8a
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:591:17
  11:     0x55d30e20501d - std::panicking::begin_panic_handler::{{closure}}::h9b9fecf185178864
  12:     0x55d30e204f8c - std::sys_common::backtrace::__rust_end_short_backtrace::h57be46a42dc7f24b
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d30e204f3d - rust_begin_unwind
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:493:5
  14:     0x55d30e1e7110 - std::panicking::begin_panic_fmt::h12277576db89392f
                               at /rustc/8e54a21139ae96a2aca3129100b057662e2799b9/library/std/src/panicking.rs:435:5
  15:     0x55d30dfad08e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h73e1e5e6d0ad4c69
  16:     0x55d30dfd1a47 - ssserver::main::hc9c5e1c75156f579
  17:     0x55d30df76266 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4006b27fbd5b2c1f
  18:     0x55d30dfd73f8 - main
  19:     0x7f0dc797309b - __libc_start_main
  20:     0x55d30df5ab29 - _start
  21:                0x0 - <unknown>
Aborted

```
